ALTER TABLE raw_detections
  ADD COLUMN IF NOT EXISTS bbox_x1 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_y1 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_x2 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bbox_y2 DOUBLE PRECISION;
